msm8996-common: Fix manifest for drm
* Fix build error:
ERROR: files are incompatible: Device manifest and framework compatibility matri
x are incompatible: HALs incompatible. Matrix level = 3. Manifest level = 3. The
 following requirements are not met:
android.hardware.drm:
    required:
        @1.0-2::IDrmFactory/.* OR
        @1.3-4::IDrmFactory/.*
    provided: IDrmFactory/clearkey (@1)
android.hardware.drm:
    required:
        @1.0-2::ICryptoFactory/.* OR
        @1.3-4::ICryptoFactory/.*
    provided: IDrmFactory/clearkey (@1)
: Success

Compressing system.new.dat with brotli
Compressing vendor.new.dat with brotli
08:48:41 ninja failed with: exit status 1